### ISSUE TITLE
sign error with url local server on v2.9

### ISSUE THREAD

**Issue by westyles** [mtrojnar/osslsigncode#414] opened 2024-11-25 21:53 UTC
Hello :)
Got time to try the new version, and immediately on the first test an error :(
without local server with Built-In TSA all ok

but with local server:
on v2.8 all ok
on v2.9+ error

Tried with all old dlls, and with all new dlls, for v2.8 and v2.9+
The problem starts with v2.9
What could be the problem?
According to the error code from libcrypto-3-x64.dll
Same with -ts "http://localhost/TS-SHA256/2017-01-03T00:00:00"

```
del /f /q vfd_*.sys
osslsigncode sign  -in vfd.sys -out vfd_2.sys -h sha1 -t "http://localhost/TS-SHA1/2017-01-03T00:00:00" -spc Client+Int.crt -key Client.key  -nolegacy
```
[https://i.imgur.com/YyzuQSl.png](https://i.imgur.com/YyzuQSl.png)

```
Connecting to http://localhost/TS-SHA1/2017-01-03T00:00:00
Authenticode timestamping failed
Use the "-ts" option to add the RFC3161 Time-Stamp Authority or choose another one Authenticode Time-Stamp Authority
Unable to set unauthenticated attributes
5C160000:error:1E08010C:DECODER routines:OSSL_DECODER_from_bio:unsupported:crypto\encode_decode\decoder_lib.c:102:No supported data to decode.  Input type: DER, Input structure: type-specific
5C160000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1188:
5C160000:error:0688010A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:613:
5C160000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1188:
5C160000:error:0688010A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:349:Type=RSAPrivateKey
5C160000:error:068000A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1188:
5C160000:error:0688010A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:349:Type=PKCS8_PRIV_KEY_INFO
5C160000:error:1E80007D:HTTP routines:OSSL_parse_url:invalid url path:crypto\http\http_lib.c:133:
5C160000:error:1E800065:HTTP routines:OSSL_parse_url:error parsing url:crypto\http\http_lib.c:179:
Failed
```

**Comment by olszomal** [comment] 2024-11-27 12:05
Could you please run the following steps and share the output of the OpenSSL commands?

- Create a timestamp query file:
```
openssl ts -query -data vfd.sys -sha1 -cert -out test.tsq
```
- Send the query and retrieve the response:
```
curl -H 'Content-Type: application/timestamp-query' \
     -H 'Accept: application/timestamp-reply' \
     --data-binary '@test.tsq' \
     'http://localhost/TS-SHA1/2017-01-03T00:00:00' \
     --output test.tsr
```
- Check the TSA's timestamp response:
```
openssl ts -reply -in test.tsr -text
```
- Verify the response:
```
openssl ts -verify -queryfile test.tsq -in test.tsr -CAfile TSACA.pem
```
- Parse the response:
```
openssl asn1parse -i -inform der -in test.tsr
```
This will help me identify the root cause of the problem.
Thank you!

**Comment by westyles** [comment] 2024-11-27 15:49
> Could you please run the following steps and share the output of the OpenSSL commands?

All files and console output are in the archive.
I've changed the commands a little bit because they didn't work for me. They're inside the archive.
I used openssl 3.1.5, I couldn't find 3.1.2.

Gen-TSA1.pem file contains client+int+root test certificates.
But when I sign via osslsigncode, there is no root.crt, and it was not required before: -spc Client+Int.crt
If something is wrong or missing, I can add to it or check more.

[vfd.zip](https://github.com/user-attachments/files/17936827/vfd.zip)

**Comment by olszomal** [comment] 2024-12-02 12:47
Since version 2.9, the native HTTP client with OpenSSL 3.x is used, and the libcurl dependency has been removed.

The issue occurs when the URL does not explicitly specify a port and includes a timestamp in ISO 8601 format in the path component. In this case, the OpenSSL function `OSSL_parse_url()` fails to parse the URL correctly.

**Workaround**
To resolve this, explicitly specify the port in the URL:
```
http://localhost:80/TS-SHA1/2017-01-03T00:00:00
```

**Comment by westyles** [comment] 2024-12-02 14:14
> Workaround
It works, thank you!

**Comment by olszomal** [comment] 2024-12-02 14:17
I suggest closing this issue.

**Closed** 2024-12-02 14:22 UTC
