### ISSUE TITLE
static binary with musl?

### ISSUE THREAD

**Issue by realkarmakun** [mtrojnar/osslsigncode#261] opened 2023-04-27 11:58 UTC
Would make much easier to install osslsigncode in docker images as it would be just a binary drop in, without running package managers

**Comment by mtrojnar** [comment] 2023-04-28 10:07
As such a build appears to only be useful for Docker, I consider this issue a duplicate of #233.

**Closed by mtrojnar** 2023-04-28 10:07 UTC
Labels: enhancement

**Comment by realkarmakun** [comment] 2023-04-28 13:39
Static binary is not necessarily need to be used with docker image  and vice versa. It would certainly make maintaining musl based docker images (e.g. alpine) but it still has uses outside docker environment, so please don't close this.

**Comment by mtrojnar** [comment] 2023-04-28 14:40
Your answer is correct, but the question it answers is wrong.  The problem is not whether it is theoretically possible to use musl on x86_64 for anything other than Docker, but whether such a static build would have sufficiently popular applications to justify maintaining a distribution.  Bear in mind that OpenSSL 3.0 and later use providers, which are not static.
